spring:
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        jdbc:
          lob:
            non_contextual_creation: 'true'
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: